### ISSUE TITLE
Help actually using this to train YOLO

### ISSUE THREAD

**Issue by jfenton888** [UAVVaste/UAVVaste#4]
This might just be something that I am missing that should be super easy to figure out, but how can I actually use this dataset with YOLOv4? I was able to run the script (though I had to remove the f-strings because I am on Ubuntu 16.04 and python3.5) and get all the images. It seems to me that I should somehow be able to use the images and annotations pretty directly when plugging into YOLO, but the only [instructions](https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects) (or [these](https://github.com/AlexeyAB/Yolo_mark)) I found on training for the custom objects seemed like I would have to do the bounding boxes manually for each. My understanding is that the end goal of this is to get a new `.weights` file that represents both COCO and your data.
This definitely feels like something that would be super easy for someone who knew their way around YOLO and I really don't want to have to manually label all these points. Please help

**Comment by MatPiech** [comment]
Hi, now I recommend using [YOLOv5](https://github.com/ultralytics/yolov5) or even [YOLOv7](https://github.com/WongKinYiu/yolov7) because they have a PyTorch code representation. Annotations (bounding boxes) for all UAVVaste images are in [annotations.json](https://github.com/UAVVaste/UAVVaste/blob/main/annotations/annotations.json) file in COCO format. 
To use this data with the YOLO algorithm, you should convert them from COCO format to YOLO format ([here](https://github.com/tw-yshuang/coco2yolo) is an example repository that does it).
Then when you have correctly converted data (I suggest previously visualizing sample bounding boxes for both COCO and YOLO formats), starting the training process is really straightforward - follow instructions from the aforementioned repositories.
